# Generated by Django 3.2.18 on 2023-10-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_order_ordered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(max_length=200),
        ),
    ]
